---
 - hosts: zoo_servers
   become: yes
   tasks:
    - name: Add confluent key
      action: shell wget -qO - https://packages.confluent.io/deb/5.2/archive.key | sudo apt-key add -

    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://packages.confluent.io/deb/5.2 stable main
        state: present

    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Install latest version of "openjdk-8-jdk and confluent-community 2.12"
      apt:
        name:
          - openjdk-8-jdk
          - confluent-community-2.12
        state: latest